services:
  - type: web
    name: draftly-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: draftly-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: draftly-db
    databaseName: draftly
    user: draftly 